<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Управляющий-музеями." data-toc-modified-id="Управляющий-музеями.-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Управляющий музеями.</a></span></li><li><span><a href="#Создание-игры." data-toc-modified-id="Создание-игры.-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Создание игры.</a></span></li><li><span><a href="#Сладости-в-данных." data-toc-modified-id="Сладости-в-данных.-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Сладости в данных.</a></span></li><li><span><a href="#Знаменитые-Ирисы." data-toc-modified-id="Знаменитые-Ирисы.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Знаменитые Ирисы.</a></span></li></ul></div>

**HomeTask**

**Лекция 7. Визуализация на Python**

Выполните задания используя данный Notebook.ipynb. Домашнее задание предоставляется вместе с набором учебных датасетов. 
Перед началом, пожалуйста, убедитесь, что все необходимые датасеты находятся в одной папке с данным Notebook.

Следуйте поэтапно (по параграфам) данного ноутбука и заполняйте пропуски необходимым кодом для визуализации, чтобы ответить на соответствующие вопросы:
- `<your code here>` - для реализации кода (убедитесь, что код выполняется без ошибок)  
- `<your answer>` - для текстового ответа

Пожалуйста, **продублируйте ответы кратко в форме на my.tinkoff.ru/edu** - это позволит быстрее проверить вашу работу. Также **прикрепите код вашего ноутбука в формате .py** - в случае вопросов, преподаватель сможет детально посмотреть ваш код.

### Управляющий музеями.

В вашем распоряжении данные о посещении 4 музеев. Для внеочереднего заседания, вам необходимо предоставить отчёт и ответить на следующие вопросы:

In [54]:
import pandas as pd
import seaborn as sns

# загрузка данных для task № 1. Посмотрим на данные
museum_visitors = pd.read_csv('museum_visitors.csv', sep = ',')
museum_visitors.head()

,Date,Avila Adobe,Firehouse Museum,Chinese American Museum,America Tropical Interpretive Center
0,2014-01-01,24778,4486,1581,6602
1,2014-02-01,18976,4172,1785,5029
2,2014-03-01,25231,7082,3229,8129
3,2014-04-01,26989,6756,2129,2824
4,2014-05-01,36883,10858,3676,10694

In [55]:
# 1. В октябре 2018 года на сколько посетителей больше посетило Avila Adobe, чем Firehouse Museum?
# <your code here>

1. В октябре 2018 года на сколько посетителей больше посетило Avila Adobe, чем Firehouse Museum?

**Ответ:**

In [56]:
# Некий музей утверждает, что в 2014 году они провели мероприятие, 
# которое привлекло невероятное количество посетителей, и что им следует получить дополнительный бюджет 
# для проведения подобного мероприятия снова. 

# Другие музеи считают, что такие мероприятия не так уж важны, и бюджеты должны быть разделены исключительно 
# на основе недавних посетителей в среднем за месяц.

# Чтобы показать, как мероприятие соотносится с обычным трафиком в каждом музее, создайте необходимую диаграмму (какую?), 
# которая показывает, как количество посетителей каждого музея менялось с течением времени. 

#  <your code here>

2. Какой график вы выберете для визуализации ежемесячного трафика музеев? 

**Ответ:**

3. Исходя из этого графика, какой музей проводил мероприятие по привлечению посетителей? 

**Ответ:**

4. Исходя из этого графика, какой музей обладает выраженной сезонностью посещения? 

**Ответ:**

### Создание игры.

Ваши друзья решили создать свою собственную видеоигру! Вы - как аналитик данных, решили помочь ребятам. IGN Game Reviews собирает данные обо всех последних игровых релизах, а также о рейтинге, который они получили от экспертов, от 0 (катастрофа) до 10 (шедевр).

Вы решили использовать обзоры IGN для рекомендации дизайна будущей игры. К счастью, рейтинг уже обобщён в CSV-файле:

In [57]:
# загрузка данных для task № 2. Посмотрим на данные
ign_data = pd.read_csv('ign_scores.csv', index_col = 'Platform', sep = ',')
ign_data.head()
#  <your code here>

,Action,"Action, Adventure",Adventure,Fighting,Platformer,Puzzle,RPG,Racing,Shooter,Simulation,Sports,Strategy
Platform,,,,,,,,,,,,
Dreamcast,6.882857,7.511111,6.281818,8.200000,8.340000,8.088889,7.700000,7.042500,7.616667,7.628571,7.272222,6.433333
Game Boy Advance,6.373077,7.507692,6.057143,6.226316,6.970588,6.532143,7.542857,6.657143,6.444444,6.928571,6.694444,7.175000
Game Boy Color,6.272727,8.166667,5.307692,4.500000,6.352941,6.583333,7.285714,5.897436,4.500000,5.900000,5.790698,7.400000
GameCube,6.532584,7.608333,6.753846,7.422222,6.665714,6.133333,7.890909,6.852632,6.981818,8.028571,7.481319,7.116667
Nintendo 3DS,6.670833,7.481818,7.414286,6.614286,7.503448,8.000000,7.719231,6.900000,7.033333,7.700000,6.388889,7.900000

1. Какую самую высокую среднюю оценку получили игры для ПК (для любого жанра)?

**Ответ:**

In [58]:
import matplotlib.pyplot as plt
import plotly.express as px 
# Гоночная игра Mario Kart Wii, выпущенная для платформы Wii в 2008 году - отличная игра
# Её рейтинг составляет колоссальные 8,9! Вдохновленные успехом этой игры, вы подумываете о собственной гоночной игре
# для платформы Wii.

# Создайте столбчатую диаграмму (barplot), которая показывает средний балл гоночных игр для каждой платформы. 
# Ваша диаграмма должна иметь по одному столбцу для каждой платформы.

#  <your code here>

2. На основе столбчатой диаграммы, ожидаете ли вы, что гоночная игра для платформы Wii получит высокий рейтинг? Если нет, то какая игровая платформа кажется лучшей альтернативой?

**Ответ:**

In [59]:
# В конце концов, вы решаете не создавать гоночную игру для Wii
# Вы решаете использовать всевозможные данные IGN, чтобы определиться с новым выбором жанра и платформы.

# Используйте данные для создания тепловой карты среднего балла по жанру и платформе. (для sns.heatmap исп. доп. annot = True)
#  <your code here>

3. Какая комбинация жанра и платформы получает самые высокие средние оценки?

**Ответ:**

4. А какая комбинация получает самые низкие средние оценки?

**Ответ:**

### Сладости в данных.

Вы работаете на крупного производителя сладостей, и ваша цель — написать отчет, который ваша компания может использовать для разработки своего следующего продукта. Вскоре после начала исследования вы натыкаетесь на этот очень интересный набор данных, содержащий результаты опроса по потреблению любимых сладостей.

In [60]:
# загрузка данных для task № 3. Посмотрим на данные
candy_data = pd.read_csv('candy.csv', index_col = 'id', sep = ',')
candy_data.head()
#  <your code here>

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
id,,,,,,,,,,,,,
0,100 Grand,Yes,No,Yes,No,No,Yes,No,Yes,No,0.732,0.860,66.971725
1,3 Musketeers,Yes,No,No,No,Yes,No,No,Yes,No,0.604,0.511,67.602936
2,Air Heads,No,Yes,No,No,No,No,No,No,No,0.906,0.511,52.341465
3,Almond Joy,Yes,No,No,Yes,No,No,No,Yes,No,0.465,0.767,50.347546
4,Baby Ruth,Yes,No,Yes,Yes,Yes,No,No,Yes,No,0.604,0.767,56.914547

In [62]:
# Чем больше сахара - тем вкуснее?

# Создайте диаграмму рассеяния (scatter plot), которая показывает связь между «sugarpercent» (на горизонтальной оси x)
# и «winpercent» (на вертикальной оси y).

#  <your code here>

In [63]:
# Похоже, что только диаграммы рассеяния недостаточно, давайте построим её с линией регресси (regplot).
# Согласно графику который вы получите, есть ли небольшая корреляция между 'winpercent' и 'sugarpercent'? 
# Что это говорит вам о конфетах, которые люди предпочитают?

#  <your code here>

1. Ответьте в свободном формате, на основании построенных графиков: **есть ли какая-то связь между предпочтениями покупателей и количеством сахара в сладостях?**

**Ответ:**

In [64]:
# Ниже создайте диаграмму рассеяния, чтобы показать связь между «pricepercent» (на горизонтальной оси x) 
# и «winpercent» (на вертикальной оси y). Используйте столбец «chocolate» для цветовой кодировки точек.

#  <your code here>

In [65]:
# Теперь давайте построим категориальную диаграмму рассеяния (график роя - swarmplot), 
# чтобы подчеркнуть связь между «chocolate» и «winpercent». 
# Поместите «chocolate» на (горизонтальную) ось x, а «winpercent» на (вертикальную) ось y.

#  <your code here>

2. Ответьте в свободном формате, на основании построенных графиков: **Как наличие шоколада влияет на предпочтения покупателей? Какой график лучше характеризует это: swarmplot или scatter plot?**

**Ответ:**

### Знаменитые Ирисы.

В набор представленных датасетов содержится показательный набор данных о замерах геометрических размеров Ирисов различных видов:
- Iris setosa
- Iris versicolor
- Iris virginica

Найдите датасет iris.csv и импортируйте для анализа в dataframe. Используйте любые графики для визуализации, чтобы ответить на вопрос:

- *Какой вид Ирисов можно определить (отделить от других видов) используя всего лишь один параметр? (и какой параметр)*

In [53]:
#  <your code here>